name: dlgp
channels:
  - defaults
dependencies:
  - python
  - pytorch
  - pip
  - pip:
    - torch
    - tokenizers
    - setuptools
    - wheel
    - transformers
    - adapter-transformers
    - datasets
    - tqdm

