training_args:
  # The NULLs are placeholders for the user to fill in by optuna hyperparameter search
  # This will be replaced in next iteration by a function
  num_train_epochs: 5
  learning_rate: null
  per_device_train_batch_size: null
  per_device_eval_batch_size: null

optuna_search_space:
  learning_rate:
    low: 1e-5
    high: 1e-3
  batch_size:
    values: [16, 32, 64, 128, 256]

optuna:
  n_trials: 2 # increase this to 10 or so
  direction: minimize

output_dir: ./training_output

defaults:
  - base_config.yaml
