training_args:
  # The NULLs are placeholders for the user to fill in by optuna hyperparameter search
  # This will be replaced in next iteration by a function
  num_train_epochs: 2
  learning_rate: null
  per_device_train_batch_size: null
  per_device_eval_batch_size: null
  weight_decay: null
  hidden_dropout_prob: null
  attention_probs_dropout_prob: null

optuna:
  n_trials: 3 # increase this to 10 or so

optuna_search_space:
  learning_rate:
    low: 1e-8
    high: 1e-3
  batch_size:
    values: [16, 32, 64]
  weight_decay:
    low: 1e-9
    high: 1e-4
  hidden_dropout_prob:
    low: 0.1
    high: 0.3
  attention_probs_dropout_prob:
    low: 0.1
    high: 0.3
  num_train_epochs:
    low: 3
    high: 10

output_dir: ./training_output

defaults:
  - base_config.yaml
