# Base configuration file with common settings

training_args:
  seed: 42
  logging_strategy: 'epoch'o
  evaluation_strategy: 'epoch'
  overwrite_output_dir: true
  remove_unused_columns: false
  metric_for_best_model: 'eval_macro_f1'
  greater_is_better: true,
  output_dir: null # Predefine, to be updated by trials
  disable_tqdm: true
  save_strategy: 'no' # Too heavy for current storage, and we just need baseline results, not actually using the mdel
  load_best_model_at_end: false # Cannot load best model as it is not save_strategy='no'

optuna:
  n_seeds: 5
  direction: maximize
  objective: f1
  trainer_objective: macro_f1

#TODO NOW: Make sure all the v03 models are run for 6 trials
hydra:
  run:
    dir: .
  job:
    chdir: false

base_output_dir: ./training_output
seeds: [42, 128, 9091, 746483, 8937216]