training_args:
  # The NULLs are placeholders for the user to fill in by optuna hyperparameter search
  # This will be replaced in next iteration by a function
  learning_rate: null
  num_train_epochs: 10
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  logging_steps: 100
  warmup_steps: 500
  eval_steps: 100
  load_best_model_at_end: true
  output_dir: null
  overwrite_output_dir: true
  evaluation_strategy: 'steps'
  save_strategy: 'steps'
  remove_unused_columns: false
