defaults:
  - _self_

learning_rate: 1e-4
num_train_epochs: 6
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
logging_steps: 200
output_dir: "./training_output"
overwrite_output_dir: true
remove_unused_columns: false
