defaults:
- base_config.yaml
optuna:
  n_seeds: 5
  n_trials: 3
  trainer_objective: micro_f1
output_dir: ./training_output
training_args:
  disable_tqdm: false
  learning_rate: 0.00022351160687559749
  num_train_epochs: 8
  per_device_eval_batch_size: 15
  per_device_train_batch_size: 15
