defaults:
- base_config.yaml
optuna:
  n_seeds: 5
  n_trials: 3
output_dir: ./training_output
training_args:
  disable_tqdm: false
  learning_rate: 0.0003932385624289287
  num_train_epochs: 15
  per_device_eval_batch_size: 15
  per_device_train_batch_size: 32
